name: pipeline_unit

on:
  push:
    branches:
      - main
      - pipeline-update
  pull_request:
    branches:
      - main
      - pipeline-update

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - name: Clonar repositório
        uses: actions/checkout@v4

      # Define a versão do Node
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Cache
      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Instala dependências
      - name: Instalar dependências
        run: npm ci

      # Gera cliente do Prisma
      - name: Gerar Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: "postgresql://user:pass@localhost:5432/db"

      # Build
      - name: Build
        run: npm run build

      # Testes
      - name: Testes
        run: npm run test:cov