name: E2E Tests

on:
  push:
    branches:
      - main
      - pipeline-update
  pull_request:
    branches:
      - main
      - pipeline-update


jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      #Clona o repositório
      - name: Clonar repositório
        uses: actions/checkout@v4

      #Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      #Instala dependências
      - name: Instalar dependências
        run: npm ci

      #Cliente prisma 
      - name: Prisma generate
        run: npx prisma generate
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/test"

      #Rodar migrations
      - name: Migrate
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/test"

      #Rodar testes E2E
      - name: Rodar E2E
        run: npm run test:e2e
        env:
          DATABASE_URL: "mysql://root:root@localhost:3306/test"
